name: Hide Flag With Noise
on: push
jobs:
  spam_commits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dark_nexus_CTF
          fetch-depth: 0
      - name: Create 70 automated commits
        run: |
          git config --global user.name "fkmrshl"
          git config --global user.email "fkmrshl@example.com"
          for i in {1..70}; do
            echo "Noise build log entry $i" >> changelog_noise.txt
            git add changelog_noise.txt
            git commit -m "Code optimization and refactoring (patch $i)"
          done
          git push origin dark_nexus_CTF
